export const ACTIVITY = [
  {
    id: 1,
    activity: "Weights",
    date: "11/28/2022",
    duration: 1,
    notes: "Upper 1",
  },
  {
    id: 2,
    activity: "Gi BJJ",
    date: "11/29/2022",
    duration: 1,
    notes: "Collar choke / chasing the back",
  },
  {
    id: 3,
    activity: "No Gi",
    date: "11/29/2022",
    duration: 1,
    notes: "Guillotines from headstrap, high elbow/push variation",
  },
  {
    id: 4,
    activity: "Weights",
    date: "11/30/2022",
    duration: 1,
    notes: "Lower 2",
  },
  {
    id: 5,
    activity: "No Gi",
    date: "12/1/2022",
    duration: 1,
    notes:
      "Attacking 1/4 guard 1) w/ shallow underhook and crossface 2) backstep to saddle heel hook 3) backstep to saddle double trouble",
  },
  {
    id: 6,
    activity: "Gi BJJ",
    date: "12/1/2022",
    duration: 1,
    notes: "Pin one leg and jump and leg drag other leg / leg drag defense",
  },
  {
    id: 7,
    activity: "Gi BJJ",
    date: "12/3/2022",
    duration: 1,
    notes: "Open mat",
  },
  {
    id: 8,
    activity: "Gi BJJ",
    date: "12/12/2022",
    duration: 1,
    notes:
      "DLR w/ pants grip to shin on shin. 1) standup/take pant/collar grip take down 2) single leg x",
  },
  {
    id: 9,
    activity: "Gi BJJ",
    date: "12/13/2022",
    duration: 1,
    notes:
      "1) Breaking spider-lasso guard to throw by. 2) when opponent granbys stack leg drag to x hook backtake",
  },
  {
    id: 10,
    activity: "No Gi",
    date: "12/13/2022",
    duration: 1,
    notes: "false reap sweep to saddle then heel hook. loose passing",
  },
  {
    id: 11,
    activity: "No Gi",
    date: "12/14/2022",
    duration: 1,
    notes:
      "shin on shin to DLR. finishing option side sweep knockdown or caio terra ankle lock. Injured thumb",
  },
  {
    id: 12,
    activity: "Weights",
    date: "12/18/2022",
    duration: 1,
    notes: "Upper 1. Bench 22.5kg 3x5",
  },
  {
    id: 13,
    activity: "Weights",
    date: "12/19/2022",
    duration: 1,
    notes: "Lower 1. Squat 30kg 3x5",
  },
  {
    id: 14,
    activity: "Gi BJJ",
    date: "12/19/2022",
    duration: 1,
    notes:
      "DLR pass using kicking back and across to remove the hook to torreando",
  },
  {
    id: 15,
    activity: "Gi BJJ",
    date: "12/20/2022",
    duration: 1,
    notes:
      "DLR pass using kicking back and across to remove the hook to torreando",
  },
  {
    id: 16,
    activity: "Gi BJJ",
    date: "12/20/2022",
    duration: 1,
    notes:
      "passing sitting guard. collar grip knee cut. weave the leg torreando. diving kimura.",
  },
  {
    id: 17,
    activity: "No Gi",
    date: "12/20/2022",
    duration: 1,
    notes: "Leg drag to saddle. leg weave pass, underhook counter to darce.",
  },
  {
    id: 18,
    activity: "Weights",
    date: "12/23/2022",
    duration: 1,
    notes: "Upper 2",
  },
  {
    id: 19,
    activity: "Gi BJJ",
    date: "12/26/2022",
    duration: 1,
    notes: "Lasso X-guard sweep",
  },
  {
    id: 20,
    activity: "Weights",
    date: "1/4/2023",
    duration: 1,
    notes: "Switched to Greg Nuckols program. Did Squats Week 1 Day 1",
  },
  {
    id: 21,
    activity: "No Gi",
    date: "1/5/2022",
    duration: 1,
    notes:
      "Wrestling exchange, to snap down. Chinstrap control and transition to the back with the side on turtle back take or trap the blocking arm and transition to top crucifix armbar.",
  },
  {
    id: 22,
    activity: "Gi BJJ",
    date: "1/5/2022",
    duration: 1,
    notes:
      "Butterfly ashi ankle lock. Sandwich principle and following the knee with your nose to help with breaking mechanics.",
  },
  {
    id: 23,
    activity: "Weights",
    date: "1/6/2022",
    duration: 1,
    notes: "Week 1 Squats[2] / Bench[1]",
  },
  {
    id: 24,
    activity: "Gi BJJ",
    date: "1/6/2022",
    duration: 1,
    notes:
      "Guest instructor: Nakai Yuki. He went over so many techniques I'm not sure if I can remember them. Mostly overunder defense half guard sweeps. crucifix attacks. lockdown.",
  },
  {
    id: 25,
    activity: "Weights",
    date: "1/8/2022",
    duration: 1,
    notes: "Week 1 Bench[2] / DL",
  },
  {
    id: 26,
    activity: "Weights",
    date: "1/11/2022",
    duration: 1,
    notes: "Week 2 Squat[1]",
  },
  {
    id: 27,
    activity: "Weights",
    date: "1/15/2022",
    duration: 1,
    notes: "Week 2 Squat[2] / Bench[1]",
  },
  {
    id: 29,
    activity: "Gi BJJ",
    date: "1/16/2022",
    duration: 2,
    notes:
      "Underhook DLR to waiter sweep. Passing SLX by clearing the leg. Or turning in and doing a top bolo",
  },
  {
    id: 30,
    activity: "Gi BJJ",
    date: "1/17/2022",
    duration: 1,
    notes: "Close guard to X-guard",
  },
  {
    id: 31,
    activity: "No Gi",
    date: "1/17/2022",
    duration: 1,
    notes: "Passing X-guard",
  },
  {
    id: 32,
    activity: "No Gi",
    date: "1/18/2022",
    duration: 1,
    notes: "Single leg to back take using half-nelson when opponent 4-points",
  },
  {
    id: 33,
    activity: "No Gi",
    date: "1/19/2022",
    duration: 1,
    notes: "Double leg. Snap-down to front headlock to crucifix armbar",
  },
  {
    id: 34,
    activity: "Gi BJJ",
    date: "1/19/2022",
    duration: 1,
    notes: "Collar sleeve to triangle",
  },
  {
    id: 35,
    activity: "No Gi",
    date: "1/25/2022",
    duration: 1,
    notes: "Wrestling 2 on 1 to single.",
  },
  {
    id: 36,
    activity: "Gi BJJ",
    date: "1/25/2022",
    duration: 1,
    notes: "Spider-lasso scissor sweep to SLX. SLX to BA footlock",
  },
  {
    id: 37,
    activity: "No Gi",
    date: "1/26/2022",
    duration: 1,
    notes: "50/50 heel hook/toehold",
  },
  {
    id: 38,
    activity: "Gi BJJ",
    date: "1/26/2022",
    duration: 1,
    notes: "Pant grip DLR to X-guard technical standup sweep",
  },
  {
    id: 39,
    activity: "Weights",
    date: "1/30/2022",
    duration: 1,
    notes:
      "Week 3 Bench [2] / DL. Injured while doing DL. Might have had bad form.",
  },
  {
    id: 40,
    activity: "Gi BJJ",
    date: "1/31/2022",
    duration: 1,
    notes: "Pendulum sweep",
  },
  {
    id: 41,
    activity: "No Gi",
    date: "1/31/2022",
    duration: 1,
    notes: "Pendulum sweep",
  },
  {
    id: 42,
    activity: "No Gi",
    date: "2/2/2022",
    duration: 1,
    notes: "Underhook DLR to waiter",
  },
  {
    id: 43,
    activity: "Weights",
    date: "2/3/2022",
    duration: 1,
    notes: "Tested for new Squat 1RM @ 110KG",
  },
  {
    id: 44,
    activity: "Gi BJJ",
    date: "2/6/2022",
    duration: 2,
    notes:
      "Basic class: Passing underhook DLR. Adv class: Berimbolo counter using the stepover bellydown ankle lock",
  },
];

export default ACTIVITY;
