const COMP_RECORD = [
  {
    id: 1,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "No Gi - Novice",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Armbar",
  },
  {
    id: 2,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "No Gi - Novice",
    weightClass: "Feather",
    weight: "149",
    result: "L",
    method: "Guillotine Choke",
  },
  {
    id: 3,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Armbar",
  },
  {
    id: 4,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Points",
  },
  {
    id: 5,
    name: "Vanguard Battle Royal Beginner + Intermediate Sub-Only Fall Tournament",
    date: "9/28/19",
    division: "No Gi - Beginner",
    weightClass: "Light",
    weight: "155",
    result: "W",
    method: "Darce Choke",
  },
  {
    id: 6,
    name: "Vanguard Battle Royal Beginner + Intermediate Sub-Only Fall Tournament",
    date: "9/28/19",
    division: "No Gi - Beginner",
    weightClass: "Light",
    weight: "155",
    result: "W",
    method: "Triangle Choke",
  },
  {
    id: 7,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "W",
    method: "Walkover",
  },
  {
    id: 8,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "W",
    method: "Points",
  },
  {
    id: 9,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "L",
    method: "Decision",
  },
  {
    id: 10,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "L",
    method: "Armbar",
  },
];

export default COMP_RECORD;